---
- name: Provision TruckCo web server
  hosts: truckco
  become: true
  vars:
    web_root: /var/www/html
    index_file: index.html

  tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Ensure no password authentication for SSH and disable root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        create: false
        backup: true
      with_items:
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
      notify: Restart ssh

    - name: Ensure SSH key auth is allowed
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        backup: true
      notify: Restart ssh

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure nginx is enabled and started
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true

    - name: Create webroot directory
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Deploy application stub index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{ web_root }}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Install ufw
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true

    - name: Allow SSH through UFW
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Allow HTTP through UFW
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Ensure UFW is enabled
      community.general.ufw:
        state: enabled

  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted
